apiVersion: apps/v1
kind: Deployment
metadata:
  name: avmtradereporter-subscriber
  namespace: biatec-scan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avmtradereporter-subscriber
  template:
    metadata:
      labels:
        app: avmtradereporter-subscriber
    spec:
      containers:
        - name: subscriber
          image: scholtz2/avm-trade-reporter-subscriber:1.2025.11.10-main
          envFrom:
            - secretRef:
                name: avm-trade-reporter-subscriber-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      restartPolicy: Always
